### PR TITLE
STUD-785 Added WK CI

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

Adding WK CI so that it builds correctly

## Solution

High level overview of what was done. This is the roadmap for those who are going to CR.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

- [x] `GO111MODULE="off" go build ./...` runs successfully

> **Note:** This may fail at first if you don't have the necessary dependencies. It will give you an error similar to the following:
>
> ```console
> $ GO111MODULE="off" go build ./...
> read_unix.go:9:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
> 	/Users/joecotton/.gvm/gos/go1.18.3/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
> 	/Users/joecotton/.gvm/pkgsets/go1.18.3/global/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
> ```
>
> To fix this, simply `go get` the missing dependency:
>
> ```console
> $ GO111MODULE="off" go get golang.org/x/crypto/ssh/terminal
> ```

- [ ] Build passes
- [ ] Skynet passes
- [ ] Aviary passes
- [ ] Rosie runs her checks

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(1) Security relevant changes were detected</summary>
<li>Watched file <code>aviary.yaml</code> added</li>
</details>

## Action Items
* Request infosec review via Slack: #support-infosec
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by alexwang-wk — APPROVED** [review]
+1 looks good to me

**Comment by alexwang-wk** [comment]
and qa +1. `GO111MODULE="off" go build ./...` runs successfully

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
